version: '3.8'
services:
  db:
    image: postgres:13.2
    ports:
      - 5449:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: decode
    volumes:
      - db-data:/var/lib/postgresql/data:rw
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/decode:delegated
    links:
      - db
    environment:
      DATABASE_URL: "postgresql://root:root@db:5432/decode"
      APP_URL: "http://decode.local:8099"
      APP_ENV: "dev"
      APP_SECRET: "f20622863e5b131a27cc1d6a4d13b735"
      APP_HOSTNAME: "decode.local"
  nginx:
    image: nginx:1.19
    ports:
      - "8099:80"
    volumes:
      - .:/var/www/decode:delegated
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
volumes:
  db-data: