parameters:

services:
    _defaults:
        autowire: trues
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Sql\Application\Controller\TestController:
        tags:
            - { name: 'controller.service_arguments' }
